repos:
  - repo: https://github.com/pycqa/pylint
    rev: pylint-2.7.0
    hooks:
      - files: ^git_plan/
        id: pylint
        stages: [commit]
        types: [file, python]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.812"
    hooks:
      - files: ^git_plan/
        id: mypy
        stages: [commit]
        types: [file, python]
  - repo: local
    hooks:
      - id: tox
        name: tox
        entry: tox
        language: system
        pass_filenames: false
        stages: [push]
